name: Deploy MultiDocker
on:
  push:
    branches:
      - main # check your repo, your default branch might be master!

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - run: docker build -t soniagurram/react-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true soniagurramavari/react-test npm test

      - run: docker build -t soniagurramavari /multi-client ./client
      - run: docker build -t soniagurramavari/multi-nginx ./nginx
      - run: docker build -t soniagurramavari/multi-server ./server
      - run: docker build -t soniagurramavari/multi-worker ./worker

      - run: docker push soniagurramavari/multi-docker/multi-client
      - run: docker push soniagurramavari/multi-docker/multi-nginx
      - run: docker push soniagurramavari/multi-docker/multi-server
      - run: docker push soniagurramavari/multi-docker/multi-worker
