name: Deploy MultiDocker
on:
  push:
    branches:
      - master # Change to 'main' if your default branch is 'main'

jobs:
  build:
    runs-on: windows-latest
    steps:
      # Checkout repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and Test React App (Client)
      - name: Build React Test Image
        run: docker build -t soniagurramavari/react-test -f ./client/Dockerfile.dev ./client
      
      - name: Run React Tests
        run: docker run -e CI=true soniagurramavari/react-test npm test

      # Build Docker Images for All Services
      - name: Build Multi-Client Image
        run: docker build -t soniagurramavari/multi-client ./client

      - name: Build Multi-Nginx Image
        run: docker build -t soniagurramavari/multi-nginx ./nginx

      - name: Build Multi-Server Image
        run: docker build -t soniagurramavari/multi-server ./server

      - name: Build Multi-Worker Image
        run: docker build -t soniagurramavari/multi-worker ./worker

      # Push All Images to Docker Hub
      - name: Push Docker Images
        run: |
          docker push soniagurramavari/multi-client
          docker push soniagurramavari/multi-nginx
          docker push soniagurramavari/multi-server
          docker push soniagurramavari/multi-worker
